import {
  aiChat,
  aiEmbed,
  getDocument,
  markDocumentIndexed,
  planDocumentChunks,
  storeDocumentEmbedding,
  updateAutoTags,
} from '../../api'
import type { AIProvider, Task } from '../../types'
import { buildAutoTagPrompt, mergeAutoTags, parseAutoTagResponse } from '../ai/autoTag'
import type { TaskHandler } from './taskWorker'

/** Task kinds handled by the background worker. */
export const TASK_KIND_EMBED = 'embedding.index'
export const TASK_KIND_AUTO_TAG = 'autotag.generate'

function parsePayload(task: Task): Record<string, unknown> {
  try {
    const value: unknown = JSON.parse(task.payload || '{}')
    return typeof value === 'object' && value !== null ? (value as Record<string, unknown>) : {}
  } catch {
    return {}
  }
}

function requireDocumentId(task: Task): string {
  const id = task.documentId ?? parsePayload(task).documentId
  if (typeof id !== 'string' || id.length === 0) {
    throw new Error('task is missing documentId')
  }
  return id
}

/**
 * Embed one document, one vector per chunk, and record the index state.
 *
 * The plan is produced by the backend so chunking matches the Rust tests, and
 * `alreadyIndexed` makes re-runs cheap. Failure is recorded against the document
 * so a partially indexed corpus stays diagnosable.
 */
export function createEmbeddingHandler(provider: AIProvider): TaskHandler {
  const model = provider.embeddingModel
  // Callers only register this handler when an embedding model exists; fail
  // loudly rather than silently indexing nothing.
  if (!model) throw new Error('provider has no embedding model configured')
  return async (task: Task) => {
    const documentId = requireDocumentId(task)

    const plan = await planDocumentChunks(documentId, model)
    if (plan.chunks.length === 0) {
      await markDocumentIndexed({
        documentId,
        model,
        contentHash: plan.contentHash,
        chunkCount: 0,
        status: 'READY',
      })
      return
    }
    if (plan.alreadyIndexed) return

    const vectors = await aiEmbed(provider.id, plan.chunks.map(chunk => chunk.text))
    if (vectors.length !== plan.chunks.length) {
      throw new Error(`embedding count mismatch: expected ${plan.chunks.length}, got ${vectors.length}`)
    }
    await Promise.all(
      plan.chunks.map((chunk, index) =>
        storeDocumentEmbedding(documentId, chunk.chunkIndex, model, chunk.excerpt, vectors[index]),
      ),
    )
    await markDocumentIndexed({
      documentId,
      model,
      contentHash: plan.contentHash,
      chunkCount: plan.chunks.length,
      status: 'READY',
    })
  }
}

/**
 * Derive tags from the document body and merge them with the user's own tags.
 *
 * Existing tags always win: generated tags are prepended and `mergeAutoTags`
 * de-duplicates, so a user-curated tag is never dropped. Any failure is recorded
 * by the task queue rather than blocking the save that queued it.
 */
export function createAutoTagHandler(provider: AIProvider): TaskHandler {
  return async (task: Task) => {
    const documentId = requireDocumentId(task)
    const document = await getDocument(documentId)
    const markdown = document.markdown ?? document.summary ?? ''
    if (markdown.trim().length === 0) return

    const request = buildAutoTagPrompt({
      markdown,
      existingTags: document.tags,
      title: document.title,
    })
    const response = await aiChat(provider.id, request)
    const generated = parseAutoTagResponse(response.content)
    if (generated.length === 0) return
    // Preserve any tags generated by a previous run; `mergeAutoTags` also keeps
    // the user's own curated tags, which must never be dropped.
    const merged = mergeAutoTags(generated, document.autoTags ?? [])
    await updateAutoTags(documentId, merged)
  }
}

/** Build the handler map for the configured provider. */
export function createTaskHandlers(provider: AIProvider): Record<string, TaskHandler> {
  const handlers: Record<string, TaskHandler> = {
    [TASK_KIND_AUTO_TAG]: createAutoTagHandler(provider),
  }
  if (provider.embeddingModel) {
    handlers[TASK_KIND_EMBED] = createEmbeddingHandler(provider)
  }
  return handlers
}