import { FormEvent, useEffect, useMemo, useState } from 'react'
import { ArrowLeft, ArrowRight, Bot, BookOpen, ChevronDown, Clock3, Globe2, Home, Library, MoreHorizontal, Plus, RefreshCw, Search, Settings, ShieldCheck, Sparkles, Star, X, PanelRightClose, Languages, Tags, Save, FileText, Check, LoaderCircle } from 'lucide-react'
import type { BrowserTab, Document, View } from './types'
import { demoDocuments } from './mock'
import { listDocuments, saveDocument } from './api'

const initialTabs:BrowserTab[]=[{id:'new',url:'',title:'New tab',loading:false,active:true,pinned:false}]

export default function App(){
 const [view,setView]=useState<View>('browser'); const [tabs,setTabs]=useState(initialTabs); const [address,setAddress]=useState(''); const [aiOpen,setAiOpen]=useState(true); const [aiMode,setAiMode]=useState<'summary'|'ask'|'translate'>('summary'); const [docs,setDocs]=useState<Document[]>(demoDocuments); const [query,setQuery]=useState(''); const [saving,setSaving]=useState(false); const [toast,setToast]=useState('');
 const active=tabs.find(t=>t.active)??tabs[0];
 useEffect(()=>{listDocuments().then(setDocs).catch(()=>{})},[])
 function notify(message:string){setToast(message);window.setTimeout(()=>setToast(''),2400)}
 function navigate(e:FormEvent){e.preventDefault();if(!address.trim())return;const url=/^https?:\/\//.test(address)?address:`https://www.google.com/search?q=${encodeURIComponent(address)}`;setTabs(ts=>ts.map(t=>t.active?{...t,url,title:address,loading:true}:t));setTimeout(()=>setTabs(ts=>ts.map(t=>t.active?{...t,loading:false}:t)),700)}
 function addTab(){setTabs(ts=>[...ts.map(t=>({...t,active:false})),{id:crypto.randomUUID(),url:'',title:'New tab',loading:false,active:true,pinned:false}]);setAddress('');setView('browser')}
 function closeTab(id:string){setTabs(ts=>{const left=ts.filter(t=>t.id!==id);if(!left.length)return initialTabs; if(ts.find(t=>t.id===id)?.active)left[left.length-1].active=true;return [...left]})}
 async function save(){setSaving(true);try{const item=await saveDocument({title:active.title==='New tab'?'Untitled page':active.title,url:active.url||'about:blank',markdown:'Captured page content will be extracted by the Reader pipeline.',tags:['Inbox']});setDocs(d=>[item,...d]);notify('Saved to knowledge base')}catch{notify('Saved locally (API is offline)')}finally{setSaving(false)}}
 return <div className="app-shell">
  <Sidebar view={view} onChange={setView}/>
  <main className="workspace">
   {view==='browser'&&<>
    <TabStrip tabs={tabs} add={addTab} close={closeTab} activate={id=>{setTabs(ts=>ts.map(t=>({...t,active:t.id===id})));const t=tabs.find(x=>x.id===id);setAddress(t?.url??'')}}/>
    <Toolbar address={address} setAddress={setAddress} navigate={navigate} loading={active.loading} aiOpen={aiOpen} setAiOpen={setAiOpen}/>
    <div className="content-split"><BrowserCanvas active={active} onAddress={v=>setAddress(v)} onNavigate={navigate}/>{aiOpen&&<AIPanel mode={aiMode} setMode={setAiMode} save={save} saving={saving}/>}</div>
   </>}
   {view==='library'&&<LibraryView docs={docs}/>} {view==='search'&&<SearchView docs={docs} query={query} setQuery={setQuery}/>} {view==='ai'&&<AIView docs={docs}/>} {view==='settings'&&<SettingsView/>}
  </main>{toast&&<div className="toast"><Check size={16}/>{toast}</div>}
 </div>
}

function Sidebar({view,onChange}:{view:View;onChange:(v:View)=>void}){const items:[View,typeof Home,string][]=[['browser',Home,'Browser'],['library',Library,'Library'],['search',Search,'Search'],['ai',Sparkles,'AI Research']];return <aside className="sidebar"><div className="brand"><div className="brand-mark"><Sparkles size={18}/></div><span>Arcadia</span></div><nav>{items.map(([id,Icon,label])=><button key={id} className={view===id?'active':''} onClick={()=>onChange(id)}><Icon size={18}/><span>{label}</span></button>)}</nav><div className="side-spacer"/><div className="privacy-card"><div><ShieldCheck size={18}/><b>Protection on</b></div><span>43 requests blocked</span></div><button className={`settings-link ${view==='settings'?'active':''}`} onClick={()=>onChange('settings')}><Settings size={18}/>Settings</button><div className="profile"><div className="avatar">CF</div><div><b>Charles</b><span>Local workspace</span></div><MoreHorizontal size={17}/></div></aside>}

function TabStrip({tabs,add,close,activate}:{tabs:BrowserTab[];add:()=>void;close:(id:string)=>void;activate:(id:string)=>void}){return <div className="tab-strip">{tabs.map(t=><button key={t.id} className={`tab ${t.active?'active':''}`} onClick={()=>activate(t.id)}><Globe2 size={14}/><span>{t.title}</span><X size={13} onClick={e=>{e.stopPropagation();close(t.id)}}/></button>)}<button className="icon-button" onClick={add} aria-label="New tab"><Plus size={17}/></button><div className="window-drag"/></div>}

function Toolbar({address,setAddress,navigate,loading,aiOpen,setAiOpen}:{address:string;setAddress:(v:string)=>void;navigate:(e:FormEvent)=>void;loading:boolean;aiOpen:boolean;setAiOpen:(v:boolean)=>void}){return <div className="toolbar"><button className="icon-button"><ArrowLeft/></button><button className="icon-button muted"><ArrowRight/></button><button className={`icon-button ${loading?'spin':''}`}><RefreshCw/></button><form onSubmit={navigate} className="address"><ShieldCheck size={16}/><input value={address} onChange={e=>setAddress(e.target.value)} placeholder="Search or enter address"/><Star size={17}/></form><button className="shield-stat"><ShieldCheck size={17}/><span>43</span></button><button className={`icon-button ${aiOpen?'selected':''}`} onClick={()=>setAiOpen(!aiOpen)}><PanelRightClose/></button><button className="icon-button"><MoreHorizontal/></button></div>}

function BrowserCanvas({active,onAddress,onNavigate}:{active:BrowserTab;onAddress:(v:string)=>void;onNavigate:(e:FormEvent)=>void}){if(active.url)return <div className="page-preview"><div className="article-kicker">ENGINEERING · 8 MIN READ</div><h1>{active.title}</h1><p className="lede">A focused reading surface for the page loaded in the native WebView.</p><div className="hero-art"><div className="orb one"/><div className="orb two"/><Sparkles size={64}/></div><h2>Designing systems that remember</h2><p>Knowledge tools become valuable when reading, understanding, and retrieval form one continuous loop. The browser is not merely a window onto information—it is where durable knowledge begins.</p><p>This preview represents content that the Tauri WebView will render. Reader extraction and privacy interception connect at the native boundary.</p></div>;return <div className="new-tab"><div className="welcome-icon"><Sparkles/></div><h1>Where do you want to explore?</h1><p>Read deeply. Save what matters. Ask your knowledge.</p><form onSubmit={onNavigate} className="hero-search"><Search/><input autoFocus placeholder="Search the web or enter a URL" onChange={e=>onAddress(e.target.value)}/><kbd>Enter</kbd></form><div className="quick-grid"><Quick icon={BookOpen} title="Reader mode" text="A calmer way to read"/><Quick icon={Sparkles} title="AI summary" text="Understand any page"/><Quick icon={Library} title="Knowledge base" text="Keep ideas close"/></div><div className="recent"><span>RECENTLY SAVED</span><div className="recent-row"><div><FileText/><p><b>Building reliable AI agents</b><small>Example Research · yesterday</small></p></div><div><FileText/><p><b>Tauri 2 security architecture</b><small>Engineering Notes · 2 days ago</small></p></div></div></div></div>}
function Quick({icon:Icon,title,text}:{icon:typeof BookOpen;title:string;text:string}){return <button className="quick-card"><Icon/><span><b>{title}</b><small>{text}</small></span><ArrowRight/></button>}

function AIPanel({mode,setMode,save,saving}:{mode:string;setMode:(m:'summary'|'ask'|'translate')=>void;save:()=>void;saving:boolean}){return <aside className="ai-panel"><div className="ai-head"><div><div className="ai-logo"><Sparkles size={17}/></div><b>AI Assistant</b></div><button className="icon-button"><MoreHorizontal/></button></div><div className="ai-tabs"><button className={mode==='summary'?'active':''} onClick={()=>setMode('summary')}>Summary</button><button className={mode==='ask'?'active':''} onClick={()=>setMode('ask')}>Ask</button><button className={mode==='translate'?'active':''} onClick={()=>setMode('translate')}>Translate</button></div><div className="ai-content"><div className="context-chip"><Globe2/>Current page<span>Ready</span></div><h3>Understand this page</h3><p className="muted-copy">Open an article to generate a grounded summary, ask questions, or translate selected text.</p><div className="prompt-actions"><button><Sparkles/>Summarize in 100 words</button><button><Tags/>Extract key ideas</button><button><Languages/>Translate to Chinese</button></div><div className="sample-answer"><div className="answer-label"><Bot/>AI preview</div><p>This article explores how reliable knowledge systems connect reading with structured capture and retrieval.</p><ul><li>Keep sources attached to every insight</li><li>Run expensive AI work asynchronously</li><li>Put permissions at the tool boundary</li></ul></div></div><div className="ai-footer"><button className="save-button" onClick={save} disabled={saving}>{saving?<LoaderCircle className="spin"/>:<Save/>}{saving?'Saving…':'Save to knowledge'}</button><div className="ask-box"><input placeholder="Ask about this page…"/><button><ArrowRight/></button></div></div></aside>}

function LibraryView({docs}:{docs:Document[]}){return <section className="page-view"><PageHeader eyebrow="KNOWLEDGE BASE" title="Your library" description="Everything you saved, organized and ready to rediscover." action="Add document"/><div className="stats"><Stat label="Documents" value={String(docs.length)} trend="+3 this week"/><Stat label="Collections" value="6" trend="Organized topics"/><Stat label="Words saved" value="18.4k" trend="About 74 min"/></div><div className="section-head"><h2>Recently saved</h2><button>View all <ArrowRight/></button></div><div className="doc-grid">{docs.map(d=><DocumentCard key={d.id} doc={d}/>)}</div></section>}
function PageHeader({eyebrow,title,description,action}:{eyebrow:string;title:string;description:string;action?:string}){return <header className="page-header"><div><span>{eyebrow}</span><h1>{title}</h1><p>{description}</p></div>{action&&<button className="primary"><Plus/>{action}</button>}</header>}
function Stat({label,value,trend}:{label:string;value:string;trend:string}){return <div className="stat"><span>{label}</span><strong>{value}</strong><small>{trend}</small></div>}
function DocumentCard({doc}:{doc:Document}){return <article className="doc-card"><div className="doc-cover"><FileText/><span>{doc.source??'Web article'}</span></div><div className="doc-body"><div className="tag-row">{doc.tags.slice(0,2).map(t=><span key={t}>{t}</span>)}</div><h3>{doc.title}</h3><p>{doc.summary??doc.markdown}</p><footer><span><Clock3/> {doc.wordCount.toLocaleString()} words</span><button><MoreHorizontal/></button></footer></div></article>}

function SearchView({docs,query,setQuery}:{docs:Document[];query:string;setQuery:(v:string)=>void}){const results=useMemo(()=>docs.filter(d=>(d.title+' '+d.tags.join(' ')+' '+d.summary).toLowerCase().includes(query.toLowerCase())),[docs,query]);return <section className="page-view"><PageHeader eyebrow="HYBRID SEARCH" title="Find what you know" description="Search by exact words now; semantic retrieval arrives in the next milestone."/><div className="library-search"><Search/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Try ‘Tauri security’ or ‘agent permissions’"/><span>{results.length} results</span></div><div className="search-list">{results.map(d=><div className="search-result" key={d.id}><div className="result-icon"><FileText/></div><div><div className="tag-row">{d.tags.map(t=><span key={t}>{t}</span>)}</div><h3>{d.title}</h3><p>{d.summary}</p><small>{d.source} · {d.url}</small></div><ArrowRight/></div>)}</div></section>}

function AIView({docs}:{docs:Document[]}){return <section className="page-view ai-view"><PageHeader eyebrow="KNOWLEDGE ASSISTANT" title="Ask across your library" description={`Ground every answer in your ${docs.length} saved sources.`}/><div className="research-layout"><div className="conversation"><div className="empty-ai"><div className="welcome-icon"><Bot/></div><h2>What would you like to understand?</h2><p>Compare ideas, find connections, or turn your saved reading into a research brief.</p><div className="suggestions"><button>What do my articles say about safe AI agents?</button><button>Compare Tauri and browser security approaches</button><button>Draft a brief from my MCP sources</button></div></div><div className="research-input"><input placeholder="Ask your knowledge base…"/><button><ArrowRight/></button></div></div><aside className="sources"><h3>Sources</h3><p>Relevant documents will appear here with exact passages.</p>{docs.slice(0,2).map(d=><div key={d.id}><FileText/><span><b>{d.title}</b><small>{d.source}</small></span></div>)}</aside></div></section>}

function SettingsView(){return <section className="page-view settings-view"><PageHeader eyebrow="PREFERENCES" title="Settings" description="Tune your browser, privacy, AI providers, and knowledge workflow."/><div className="settings-layout"><nav>{['General','Browser','Privacy','AI providers','Knowledge','Plugins','Advanced'].map((x,i)=><button className={i===3?'active':''} key={x}>{x}</button>)}</nav><div className="settings-card"><div className="setting-title"><div className="ai-logo"><Sparkles/></div><div><h2>AI providers</h2><p>Connect an LLM for summaries, translation, and knowledge Q&A.</p></div></div><label>Provider<select><option>Not configured</option><option>OpenAI compatible</option><option>Ollama (local)</option></select></label><label>Base URL<input placeholder="https://api.example.com/v1"/></label><label>Model<input placeholder="Choose a model"/></label><label>API key<div className="secret-row"><input type="password" placeholder="Stored in system keychain"/><button>Save securely</button></div></label><div className="notice"><ShieldCheck/><p><b>Your key stays on this device.</b><span>Credentials are stored by the operating system and never written to application logs.</span></p></div><hr/><div className="coming-soon"><div><h3>Plugins</h3><p>Plugin support is coming soon. The manifest and permission architecture is reserved, but no third-party code runs in V1.</p></div><span>0 installed</span></div></div></div></section>}
